# Generated by Django 6.0.3 on 2026-06-24 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='derpartment',
            new_name='department',
        ),
    ]
