# Generated by Django 5.2.14 on 2026-07-01 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_student_course_remove_student_roll_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phn_number',
            field=models.IntegerField(default=0),
        ),
    ]
