# Generated by Django 6.0.4 on 2026-07-02 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_student_course_remove_student_roll_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='enrollment_number',
            field=models.IntegerField(default=None, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='phn_number',
            field=models.IntegerField(default=None),
        ),
    ]
