# Generated by Django 6.0.4 on 2026-07-02 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_enrollment_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='enrollment_number',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='phn_number',
            field=models.IntegerField(default=0),
        ),
    ]
