# Generated by Django 5.2.14 on 2026-07-01 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_phn_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='enrollment_number',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
