# Generated by Django 5.2.14 on 2026-07-01 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_enrollment_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='enrollment_number',
            field=models.IntegerField(default='none', unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='phn_number',
            field=models.IntegerField(default='none'),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('students', models.ManyToManyField(related_name='courses', to='students.student')),
            ],
        ),
    ]
