# Generated by Django 5.2.14 on 2026-07-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_student_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='courses',
        ),
        migrations.AlterField(
            model_name='student',
            name='enrollment_number',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='phn_number',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
