# Generated by Django 5.2.14 on 2026-07-02 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_remove_student_courses_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.ManyToManyField(to='students.course'),
        ),
    ]
