# Generated by Django 6.0.3 on 2026-06-24 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=20, unique=True)),
                ('course_name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=150)),
                ('instructor', models.CharField(max_length=50)),
                ('duration', models.IntegerField(help_text='duration in week')),
                ('credit', models.IntegerField()),
            ],
        ),
    ]
